# Generated by Django 6.0.1 on 2026-02-03 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv_data.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv_data.store')),
            ],
            options={
                'unique_together': {('product', 'store')},
            },
        ),
    ]
